// <auto-generated />
using Insurance.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Insurance.Api.Migrations
{
    [DbContext(typeof(InsuranceDbContext))]
    [Migration("20231015142817_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("Insurance.Api.Data.Models.ProductTypeSurchargeRule", b =>
                {
                    b.Property<int>("ProductTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlatCartSurcharge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlatItemSurcharge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PercentageItemSurcharge")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductTypeId");

                    b.ToTable("ProductTypeSurchargeRules");
                });
#pragma warning restore 612, 618
        }
    }
}
